// _id: 5ee1f692695a936d38e7dc3d

// 12 bytes
// 4 bytes -> timestamp
// 3 bytes -> machine identifier
// 2 bytes -> process identifier
// 3 bytes -> counter
// ID is generated by mongo driver

const mongoose = require('mongoose');

const id = new mongoose.Types.ObjectId();
console.log(id.getTimestamp());

const isValid = mongoose.Types.ObjectId.isValid('1234');
